# Generated by Django 4.2.18 on 2025-01-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_head', models.CharField(max_length=255, verbose_name='Heading')),
                ('add_sub_head', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subheading')),
                ('add_text', models.TextField(blank=True, null=True, verbose_name='Text Description')),
                ('add_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('add_image', models.ImageField(upload_to='slider_images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='admin1.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('site_link', models.URLField()),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('no_of_ratings', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.subcategory')),
            ],
        ),
    ]
