# Generated by Django 4.2.18 on 2025-01-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
