# Generated by Django 4.2.18 on 2025-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
