# Generated by Django 4.2.18 on 2025-01-22 14:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_manufacturer_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 15, 55, 316311, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='slider',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_head',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_image',
            field=models.ImageField(upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_sub_head',
            field=models.CharField(default='Default Subheading', max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_text',
            field=models.CharField(default='Default Text', max_length=200),
        ),
    ]
