# Generated by Django 4.2.18 on 2025-01-28 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_slider_end_time_slider_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 11, 0, 2, 362330, tzinfo=datetime.timezone.utc)),
        ),
    ]
