# Generated by Django 4.2.18 on 2025-01-28 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_alter_slider_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 1, 55, 868283, tzinfo=datetime.timezone.utc)),
        ),
    ]
