# Generated by Django 4.2.18 on 2025-01-30 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_alter_slider_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 17, 57, 41, 797659, tzinfo=datetime.timezone.utc)),
        ),
    ]
