# Generated by Django 4.2.18 on 2025-01-31 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0010_alter_slider_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 10, 15, 50, 280793, tzinfo=datetime.timezone.utc)),
        ),
    ]
