# Generated by Django 4.2.18 on 2025-01-31 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0011_alter_slider_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 11, 9, 37, 418604, tzinfo=datetime.timezone.utc)),
        ),
    ]
